/*
 * Created on 2024-05-02 ( 14:45:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;

/**
 * DTO class for "PmsBrand"
 *
 * @author Telosys
 *
 */

public class PmsBrandDTO implements Serializable {

  private static final long serialVersionUID = 1L;

  // --- PRIMARY KEY
  private Long brandId;
  // --- OTHER DATA FIELDS
  private String name;
  private String logo;
  private String descript;
  private Byte showStatus;
  private String firstLetter;
  private Integer sort;

  /**
   * Constructor
   */
  public PmsBrandDTO() {
    super();
  }

  public static long getSerialversionuid() {
    return serialVersionUID;
  }

  public Long getBrandId() {
    return brandId;
  }

  public void setBrandId(Long brandId) {
    this.brandId = brandId;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getLogo() {
    return logo;
  }

  public void setLogo(String logo) {
    this.logo = logo;
  }

  public String getDescript() {
    return descript;
  }

  public void setDescript(String descript) {
    this.descript = descript;
  }

  public Byte getShowStatus() {
    return showStatus;
  }

  public void setShowStatus(Byte showStatus) {
    this.showStatus = showStatus;
  }

  public String getFirstLetter() {
    return firstLetter;
  }

  public void setFirstLetter(String firstLetter) {
    this.firstLetter = firstLetter;
  }

  public Integer getSort() {
    return sort;
  }

  public void setSort(Integer sort) {
    this.sort = sort;
  }

}
