/*
 * Created on 2024-05-02 ( 14:45:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;

import java.math.BigDecimal;


/**
 * DTO class for "PmsSkuInfo"
 *
 * @author Telosys
 *
 */
@Data
public class PmsSkuInfoDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long skuId ;
    //--- OTHER DATA FIELDS 
    private Long spuId ;
    private String skuName ;
    private String skuDesc ;
    private Long catalogId ;
    private Long brandId ;
    private String skuDefaultImg ;
    private String skuTitle ;
    private String skuSubtitle ;
    private BigDecimal price ;
    private Long saleCount ;

    /**
     * Constructor
     */
    public PmsSkuInfoDTO() {
		super();
    }
}
    

