/*
 * Created on 2024-05-02 ( 16:45:40 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;

import java.math.BigDecimal;


/**
 * DTO class for "UmsMemberStatisticsInfo"
 *
 * @author Telosys
 *
 */
@Data
public class UmsMemberStatisticsInfoDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private Long memberId ;
    private BigDecimal consumeAmount ;
    private BigDecimal couponAmount ;
    private Integer orderCount ;
    private Integer couponCount ;
    private Integer commentCount ;
    private Integer returnOrderCount ;
    private Integer loginCount ;
    private Integer attendCount ;
    private Integer fansCount ;
    private Integer collectProductCount ;
    private Integer collectSubjectCount ;
    private Integer collectCommentCount ;
    private Integer inviteFriendCount ;

    /**
     * Constructor
     */
    public UmsMemberStatisticsInfoDTO() {
		super();
    }
}
    

