/*
 * Created on 2024-05-02 ( 16:45:39 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;


/**
 * DTO class for "UmsMemberCollectSubject"
 *
 * @author Telosys
 *
 */
@Data
public class UmsMemberCollectSubjectDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private Long subjectId ;
    private String subjectName ;
    private String subjectImg ;
    private String subjectUrll ;

    /**
     * Constructor
     */
    public UmsMemberCollectSubjectDTO() {
		super();
    }
}
    

