/*
 * Created on 2024-05-02 ( 19:42:31 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;

import java.util.Date;


/**
 * DTO class for "UndoLog"
 *
 * @author Telosys
 *
 */
@Data
public class UndoLogDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private Long branchId ;
    private String xid ;
    private String context ;
    private byte[] rollbackInfo ;
    private Integer logStatus ;
    private Date logCreated ;
    private Date logModified ;
    private String ext ;

    /**
     * Constructor
     */
    public UndoLogDTO() {
		super();
    }
}
    

