/*
 * Created on 2024-05-02 ( 19:42:32 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;

import java.math.BigDecimal;


/**
 * DTO class for "WmsPurchaseDetail"
 *
 * @author Telosys
 *
 */
@Data
public class WmsPurchaseDetailDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private Long purchaseId ;
    private Long skuId ;
    private Integer skuNum ;
    private BigDecimal skuPrice ;
    private Long wareId ;
    private Integer status ;

    /**
     * Constructor
     */
    public WmsPurchaseDetailDTO() {
		super();
    }
}
    

