/*
 * Created on 2024-05-02 ( 19:42:32 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;

import java.util.Date;


/**
 * DTO class for "WmsWareOrderTask"
 *
 * @author Telosys
 *
 */
@Data
public class WmsWareOrderTaskDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private Long orderId ;
    private String orderSn ;
    private String consignee ;
    private String consigneeTel ;
    private String deliveryAddress ;
    private String orderComment ;
    private Boolean paymentWay ;
    private Byte taskStatus ;
    private String orderBody ;
    private String trackingNo ;
    private Date createTime ;
    private Long wareId ;
    private String taskComment ;

    /**
     * Constructor
     */
    public WmsWareOrderTaskDTO() {
		super();
    }
}
    

