/*
 * Created on 2024-05-02 ( 16:45:38 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import java.util.Date;
import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "UmsGrowthChangeHistory"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="ums_growth_change_history", catalog="gulimall-ums" )
public class UmsGrowthChangeHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="member_id")
    private Long       memberId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time")
    private Date       createTime ;

    @Column(name="change_count")
    private Integer    changeCount ;

    @Column(name="note", length=0)
    private String     note ;

    @Column(name="source_type")
    private Byte       sourceType ;

    /**
     * Constructor
     */
    public UmsGrowthChangeHistory() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(memberId);
  sb.append("|");
  sb.append(createTime);
  sb.append("|");
  sb.append(changeCount);
  sb.append("|");
  sb.append(note);
  sb.append("|");
  sb.append(sourceType);
  return sb.toString(); 
 } 


}
