/*
 * Created on 2024-05-02 ( 16:45:39 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import java.util.Date;
import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "UmsMemberLoginLog"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="ums_member_login_log", catalog="gulimall-ums" )
public class UmsMemberLoginLog implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="member_id")
    private Long       memberId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time")
    private Date       createTime ;

    @Column(name="ip", length=64)
    private String     ip ;

    @Column(name="city", length=64)
    private String     city ;

    @Column(name="login_type")
    private Boolean    loginType ;

    /**
     * Constructor
     */
    public UmsMemberLoginLog() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(memberId);
  sb.append("|");
  sb.append(createTime);
  sb.append("|");
  sb.append(ip);
  sb.append("|");
  sb.append(city);
  sb.append("|");
  sb.append(loginType);
  return sb.toString(); 
 } 


}
