/*
 * Created on 2024-05-02 ( 16:45:39 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import java.math.BigDecimal;
import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "UmsMemberLevel"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="ums_member_level", catalog="gulimall-ums" )
public class UmsMemberLevel implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="name", length=100)
    private String     name ;

    @Column(name="growth_point")
    private Integer    growthPoint ;

    @Column(name="default_status")
    private Byte       defaultStatus ;

    @Column(name="free_freight_point")
    private BigDecimal freeFreightPoint ;

    @Column(name="comment_growth_point")
    private Integer    commentGrowthPoint ;

    @Column(name="priviledge_free_freight")
    private Byte       priviledgeFreeFreight ;

    @Column(name="priviledge_member_price")
    private Byte       priviledgeMemberPrice ;

    @Column(name="priviledge_birthday")
    private Byte       priviledgeBirthday ;

    @Column(name="note", length=255)
    private String     note ;

    /**
     * Constructor
     */
    public UmsMemberLevel() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(name);
  sb.append("|");
  sb.append(growthPoint);
  sb.append("|");
  sb.append(defaultStatus);
  sb.append("|");
  sb.append(freeFreightPoint);
  sb.append("|");
  sb.append(commentGrowthPoint);
  sb.append("|");
  sb.append(priviledgeFreeFreight);
  sb.append("|");
  sb.append(priviledgeMemberPrice);
  sb.append("|");
  sb.append(priviledgeBirthday);
  sb.append("|");
  sb.append(note);
  return sb.toString(); 
 } 


}
