/*
 * Created on 2024-05-02 ( 16:45:40 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import java.math.BigDecimal;
import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "UmsMemberStatisticsInfo"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="ums_member_statistics_info", catalog="gulimall-ums" )
public class UmsMemberStatisticsInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="member_id")
    private Long       memberId ;

    @Column(name="consume_amount")
    private BigDecimal consumeAmount ;

    @Column(name="coupon_amount")
    private BigDecimal couponAmount ;

    @Column(name="order_count")
    private Integer    orderCount ;

    @Column(name="coupon_count")
    private Integer    couponCount ;

    @Column(name="comment_count")
    private Integer    commentCount ;

    @Column(name="return_order_count")
    private Integer    returnOrderCount ;

    @Column(name="login_count")
    private Integer    loginCount ;

    @Column(name="attend_count")
    private Integer    attendCount ;

    @Column(name="fans_count")
    private Integer    fansCount ;

    @Column(name="collect_product_count")
    private Integer    collectProductCount ;

    @Column(name="collect_subject_count")
    private Integer    collectSubjectCount ;

    @Column(name="collect_comment_count")
    private Integer    collectCommentCount ;

    @Column(name="invite_friend_count")
    private Integer    inviteFriendCount ;

    /**
     * Constructor
     */
    public UmsMemberStatisticsInfo() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(memberId);
  sb.append("|");
  sb.append(consumeAmount);
  sb.append("|");
  sb.append(couponAmount);
  sb.append("|");
  sb.append(orderCount);
  sb.append("|");
  sb.append(couponCount);
  sb.append("|");
  sb.append(commentCount);
  sb.append("|");
  sb.append(returnOrderCount);
  sb.append("|");
  sb.append(loginCount);
  sb.append("|");
  sb.append(attendCount);
  sb.append("|");
  sb.append(fansCount);
  sb.append("|");
  sb.append(collectProductCount);
  sb.append("|");
  sb.append(collectSubjectCount);
  sb.append("|");
  sb.append(collectCommentCount);
  sb.append("|");
  sb.append(inviteFriendCount);
  return sb.toString(); 
 } 


}
