/*
 * Created on 2024-05-02 ( 16:45:39 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.controllers;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com._yzhheng.rest.dto.UmsMemberCollectSpuDTO;
import com._yzhheng.rest.services.UmsMemberCollectSpuService;

@RestController
@RequestMapping(value = "api/v1/UmsMemberCollectSpu", produces = MediaType.APPLICATION_JSON_VALUE)
public class UmsMemberCollectSpuRestController {

	private static final Logger logger = LoggerFactory.getLogger(UmsMemberCollectSpuRestController.class);
	
	private UmsMemberCollectSpuService service ; // injected
	
	/**
	 * Constructor (usable for Dependency Injection)
	 *
	 * @param service
	 */
	protected UmsMemberCollectSpuRestController(UmsMemberCollectSpuService service) {
		super();
		this.service = service;
	}
    
	/**
	 * Get ALL
	 *
	 * @return
	 */
	@GetMapping("")
	protected ResponseEntity<List<UmsMemberCollectSpuDTO>> findAll() {
    	logger.debug("REST : GET - findAll");
    	List<UmsMemberCollectSpuDTO> list = service.findAll();
    	return ResponseEntity.ok(list); // always 200
    }
    
    /**
     * Get ONE identified by the given PK
	 *
	 * @param id
     * @return 200 or 404 
     */
    @GetMapping("/{id}")
    protected ResponseEntity<UmsMemberCollectSpuDTO> findById(@PathVariable Long id) {
    	logger.debug("REST : GET - findById");
    	UmsMemberCollectSpuDTO umsMemberCollectSpuDTO = service.findById(id);
		if ( umsMemberCollectSpuDTO != null ) {
			return ResponseEntity.ok(umsMemberCollectSpuDTO); // 200 OK, found
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found
		}		
    }

    
	/**
 	 * Create if doesn't exist 
	 *
	 * @param umsMemberCollectSpuDTO
	 * @return 201 created or 409 conflict
	 */
	@PostMapping("")
	protected ResponseEntity<Void> create(@RequestBody UmsMemberCollectSpuDTO umsMemberCollectSpuDTO) {
    	logger.debug("REST : POST - create");
		if ( service.create(umsMemberCollectSpuDTO) ) {
			return ResponseEntity.status(HttpStatus.CREATED).build(); // 201 created
		}
		else {
			return ResponseEntity.status(HttpStatus.CONFLICT).build(); // 409 Conflict
		}
	}

	/**
	 * Update or create
	 *
	 * @param id
	 * @param umsMemberCollectSpuDTO
	 * @return 200 updated or created
	 */
	@PutMapping("/{id}")
	protected ResponseEntity<Void> save(@PathVariable Long id, @RequestBody UmsMemberCollectSpuDTO umsMemberCollectSpuDTO) {
    	logger.debug("REST : PUT - save");
		service.save(id, umsMemberCollectSpuDTO);
		return ResponseEntity.ok().build(); // OK, updated or created
	}

	/**
 	 * Update if exists 
	 *
	 * @param umsMemberCollectSpuDTO
	 * @return 200 updated or 404 not found
	 */
	@PutMapping("")
	protected ResponseEntity<Void> update(@RequestBody UmsMemberCollectSpuDTO umsMemberCollectSpuDTO) {
    	logger.debug("REST : PUT - update");
		if ( service.update(umsMemberCollectSpuDTO) ) {
			return ResponseEntity.ok().build(); // 200 OK, found and updated
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
		}
	}

	/**
 	 * Partial update for the given PK (if it exists )
	 *
	 * @param id
	 * @param umsMemberCollectSpuDTO
	 * @return 200 updated or 404 not found
	 */
	@PatchMapping("/{id}")
	protected ResponseEntity<Void> partialUpdate(@PathVariable Long id, @RequestBody UmsMemberCollectSpuDTO umsMemberCollectSpuDTO) {
    	logger.debug("REST : PATCH - partialUpdate");
    	if ( service.partialUpdate(id, umsMemberCollectSpuDTO) ) {
    		return ResponseEntity.ok().build(); // OK, found and updated
    	}
    	else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
    	}
	}

	/**
	 * Delete by PK 
	 *
	 * @param id
	 * @return 204 deleted or 404 not found
	 */
	@DeleteMapping("/{id}")
	protected ResponseEntity<Void> deleteById(@PathVariable Long id) {
    	logger.debug("REST : DELETE - deleteById");
		if ( service.deleteById(id) ) {
			return ResponseEntity.noContent().build(); // 204 No content = "deleted"
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not deleted"
		}
	}

}
