/*
 * Created on 2024-05-02 ( 14:45:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import com._yzhheng.persistence.entities.PmsAttr;

/**
 * Spring Data JPA repository for entity "PmsAttr" <br>
 * 
 * This repository extends PagingAndSortingRepository interface <br>
 * so it provides by default all the basic CRUD operations : <br>
 * findById, findAll, save, delete, etc <br>
 * with pagination and sorting : <br>
 * findAll(Pageable), findAll(Sort)<br>
 * 
 * This repository can be extended by adding specific "finders" methods<br>
 * To do so, see the "predicates conventions" for "derived query methods" in
 * Spring Data documentation
 * 
 * @author Telosys
 *
 */
public interface PmsAttrRepository extends JpaRepository<PmsAttr, Long> {

	@Query(value = "SELECT * FROM pms_attr WHERE FIND_IN_SET(attr_id, :attrIdsInCommaFormat) AND search_type=1", nativeQuery = true)
	List<Long> getSearchableAttrByAttrIds(String attrIdsInCommaFormat);

	// Insert specific finders here

	// List<PmsAttr> findByXxx(String xxx);

	// List<PmsAttr> findByXxxStartingWith(String xxx);

	// List<PmsAttr> findByXxxContaining(String xxx);

	// List<PmsAttr> findByYyy(BigDecimal yyy);

	// List<PmsAttr> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);
}
