/*
 * Created on 2024-05-02 ( 14:45:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.repositories;

import org.springframework.data.jpa.repository.JpaRepository;

import com._yzhheng.persistence.entities.PmsSpuComment;

/**
 * Spring Data JPA repository for entity "PmsSpuComment" <br> 
 * 
 * This repository extends PagingAndSortingRepository interface <br>
 * so it provides by default all the basic CRUD operations : <br>
 *   findById, findAll, save, delete, etc <br> 
 * with pagination and sorting : <br>
 *   findAll(Pageable), findAll(Sort)<br>
 * 
 * This repository can be extended by adding specific "finders" methods<br>
 * To do so, see the "predicates conventions" for "derived query methods" in Spring Data documentation
 * 
 * @author Telosys
 *
 */
public interface PmsSpuCommentRepository extends JpaRepository<PmsSpuComment, Long> {

	// Insert specific finders here 

	//List<PmsSpuComment> findByXxx(String xxx);

	//List<PmsSpuComment> findByXxxStartingWith(String xxx);

	//List<PmsSpuComment> findByXxxContaining(String xxx);

	//List<PmsSpuComment> findByYyy(BigDecimal yyy);

	//List<PmsSpuComment> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);
}
