/*
 * Created on 2024-05-02 ( 14:45:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.repositories;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import com._yzhheng.persistence.entities.PmsSkuInfo;

/**
 * Spring Data JPA repository for entity "PmsSkuInfo" <br>
 * 
 * This repository extends PagingAndSortingRepository interface <br>
 * so it provides by default all the basic CRUD operations : <br>
 * findById, findAll, save, delete, etc <br>
 * with pagination and sorting : <br>
 * findAll(Pageable), findAll(Sort)<br>
 * 
 * This repository can be extended by adding specific "finders" methods<br>
 * To do so, see the "predicates conventions" for "derived query methods" in
 * Spring Data documentation
 * 
 * @author Telosys
 *
 */
public interface PmsSkuInfoRepository extends JpaRepository<PmsSkuInfo, Long> {

	@Query(value = "SELECT * FROM pms_sku_info where spu_id = :spuId", nativeQuery = true)
	Optional<List<PmsSkuInfo>> getAllSkuBySpuId(Long spuId);

	// Insert specific finders here

	// List<PmsSkuInfo> findByXxx(String xxx);

	// List<PmsSkuInfo> findByXxxStartingWith(String xxx);

	// List<PmsSkuInfo> findByXxxContaining(String xxx);

	// List<PmsSkuInfo> findByYyy(BigDecimal yyy);

	// List<PmsSkuInfo> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);
}
