/*
 * Created on 2024-05-02 ( 14:45:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;

import com._yzhheng.persistence.entities.PmsSpuInfo;

import jakarta.transaction.Transactional;

/**
 * Spring Data JPA repository for entity "PmsSpuInfo" <br>
 * 
 * This repository extends PagingAndSortingRepository interface <br>
 * so it provides by default all the basic CRUD operations : <br>
 * findById, findAll, save, delete, etc <br>
 * with pagination and sorting : <br>
 * findAll(Pageable), findAll(Sort)<br>
 * 
 * This repository can be extended by adding specific "finders" methods<br>
 * To do so, see the "predicates conventions" for "derived query methods" in
 * Spring Data documentation
 * 
 * @author Telosys
 *
 */
public interface PmsSpuInfoRepository extends JpaRepository<PmsSpuInfo, Long> {

	@Transactional
	@Modifying
	@Query(value = "UPDATE pms_spu_info SET publish_status = :publishStatus WHERE id = :spuId", nativeQuery = true)
	void updateSpuStatus(Long spuId, int publishStatus);

	// Insert specific finders here

	// List<PmsSpuInfo> findByXxx(String xxx);

	// List<PmsSpuInfo> findByXxxStartingWith(String xxx);

	// List<PmsSpuInfo> findByXxxContaining(String xxx);

	// List<PmsSpuInfo> findByYyy(BigDecimal yyy);

	// List<PmsSpuInfo> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);
}
