/*
 * Created on 2024-05-02 ( 15:33:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.controllers;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com._yzhheng.rest.dto.PmsAttrGroupDTO;
import com._yzhheng.rest.services.PmsAttrGroupService;

@RestController
@RequestMapping(value = "api/v1/PmsAttrGroup", produces = MediaType.APPLICATION_JSON_VALUE)
public class PmsAttrGroupRestController {

	private static final Logger logger = LoggerFactory.getLogger(PmsAttrGroupRestController.class);
	
	private PmsAttrGroupService service ; // injected
	
	/**
	 * Constructor (usable for Dependency Injection)
	 *
	 * @param service
	 */
	protected PmsAttrGroupRestController(PmsAttrGroupService service) {
		super();
		this.service = service;
	}
    
	/**
	 * Get ALL
	 *
	 * @return
	 */
	@GetMapping("")
	protected ResponseEntity<List<PmsAttrGroupDTO>> findAll() {
    	logger.debug("REST : GET - findAll");
    	List<PmsAttrGroupDTO> list = service.findAll();
    	return ResponseEntity.ok(list); // always 200
    }
    
    /**
     * Get ONE identified by the given PK
	 *
	 * @param attrGroupId
     * @return 200 or 404 
     */
    @GetMapping("/{attrGroupId}")
    protected ResponseEntity<PmsAttrGroupDTO> findById(@PathVariable Long attrGroupId) {
    	logger.debug("REST : GET - findById");
    	PmsAttrGroupDTO pmsAttrGroupDTO = service.findById(attrGroupId);
		if ( pmsAttrGroupDTO != null ) {
			return ResponseEntity.ok(pmsAttrGroupDTO); // 200 OK, found
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found
		}		
    }

    
	/**
 	 * Create if doesn't exist 
	 *
	 * @param pmsAttrGroupDTO
	 * @return 201 created or 409 conflict
	 */
	@PostMapping("")
	protected ResponseEntity<Void> create(@RequestBody PmsAttrGroupDTO pmsAttrGroupDTO) {
    	logger.debug("REST : POST - create");
		if ( service.create(pmsAttrGroupDTO) ) {
			return ResponseEntity.status(HttpStatus.CREATED).build(); // 201 created
		}
		else {
			return ResponseEntity.status(HttpStatus.CONFLICT).build(); // 409 Conflict
		}
	}

	/**
	 * Update or create
	 *
	 * @param attrGroupId
	 * @param pmsAttrGroupDTO
	 * @return 200 updated or created
	 */
	@PutMapping("/{attrGroupId}")
	protected ResponseEntity<Void> save(@PathVariable Long attrGroupId, @RequestBody PmsAttrGroupDTO pmsAttrGroupDTO) {
    	logger.debug("REST : PUT - save");
		service.save(attrGroupId, pmsAttrGroupDTO);
		return ResponseEntity.ok().build(); // OK, updated or created
	}

	/**
 	 * Update if exists 
	 *
	 * @param pmsAttrGroupDTO
	 * @return 200 updated or 404 not found
	 */
	@PutMapping("")
	protected ResponseEntity<Void> update(@RequestBody PmsAttrGroupDTO pmsAttrGroupDTO) {
    	logger.debug("REST : PUT - update");
		if ( service.update(pmsAttrGroupDTO) ) {
			return ResponseEntity.ok().build(); // 200 OK, found and updated
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
		}
	}

	/**
 	 * Partial update for the given PK (if it exists )
	 *
	 * @param attrGroupId
	 * @param pmsAttrGroupDTO
	 * @return 200 updated or 404 not found
	 */
	@PatchMapping("/{attrGroupId}")
	protected ResponseEntity<Void> partialUpdate(@PathVariable Long attrGroupId, @RequestBody PmsAttrGroupDTO pmsAttrGroupDTO) {
    	logger.debug("REST : PATCH - partialUpdate");
    	if ( service.partialUpdate(attrGroupId, pmsAttrGroupDTO) ) {
    		return ResponseEntity.ok().build(); // OK, found and updated
    	}
    	else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
    	}
	}

	/**
	 * Delete by PK 
	 *
	 * @param attrGroupId
	 * @return 204 deleted or 404 not found
	 */
	@DeleteMapping("/{attrGroupId}")
	protected ResponseEntity<Void> deleteById(@PathVariable Long attrGroupId) {
    	logger.debug("REST : DELETE - deleteById");
		if ( service.deleteById(attrGroupId) ) {
			return ResponseEntity.noContent().build(); // 204 No content = "deleted"
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not deleted"
		}
	}

}
