/*
 * Created on 2024-05-02 ( 15:33:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.controllers;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com._yzhheng.rest.dto.PmsBrandDTO;
import com._yzhheng.rest.services.PmsBrandService;

@RestController
@RequestMapping(value = "api/v1/PmsBrand", produces = MediaType.APPLICATION_JSON_VALUE)
public class PmsBrandRestController {

	private static final Logger logger = LoggerFactory.getLogger(PmsBrandRestController.class);
	
	private PmsBrandService service ; // injected
	
	/**
	 * Constructor (usable for Dependency Injection)
	 *
	 * @param service
	 */
	protected PmsBrandRestController(PmsBrandService service) {
		super();
		this.service = service;
	}
    
	/**
	 * Get ALL
	 *
	 * @return
	 */
	@GetMapping("")
	protected ResponseEntity<List<PmsBrandDTO>> findAll() {
    	logger.debug("REST : GET - findAll");
    	List<PmsBrandDTO> list = service.findAll();
    	return ResponseEntity.ok(list); // always 200
    }
    
    /**
     * Get ONE identified by the given PK
	 *
	 * @param brandId
     * @return 200 or 404 
     */
    @GetMapping("/{brandId}")
    protected ResponseEntity<PmsBrandDTO> findById(@PathVariable Long brandId) {
    	logger.debug("REST : GET - findById");
    	PmsBrandDTO pmsBrandDTO = service.findById(brandId);
		if ( pmsBrandDTO != null ) {
			return ResponseEntity.ok(pmsBrandDTO); // 200 OK, found
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found
		}		
    }

    
	/**
 	 * Create if doesn't exist 
	 *
	 * @param pmsBrandDTO
	 * @return 201 created or 409 conflict
	 */
	@PostMapping("")
	protected ResponseEntity<Void> create(@RequestBody PmsBrandDTO pmsBrandDTO) {
    	logger.debug("REST : POST - create");
		if ( service.create(pmsBrandDTO) ) {
			return ResponseEntity.status(HttpStatus.CREATED).build(); // 201 created
		}
		else {
			return ResponseEntity.status(HttpStatus.CONFLICT).build(); // 409 Conflict
		}
	}

	/**
	 * Update or create
	 *
	 * @param brandId
	 * @param pmsBrandDTO
	 * @return 200 updated or created
	 */
	@PutMapping("/{brandId}")
	protected ResponseEntity<Void> save(@PathVariable Long brandId, @RequestBody PmsBrandDTO pmsBrandDTO) {
    	logger.debug("REST : PUT - save");
		service.save(brandId, pmsBrandDTO);
		return ResponseEntity.ok().build(); // OK, updated or created
	}

	/**
 	 * Update if exists 
	 *
	 * @param pmsBrandDTO
	 * @return 200 updated or 404 not found
	 */
	@PutMapping("")
	protected ResponseEntity<Void> update(@RequestBody PmsBrandDTO pmsBrandDTO) {
    	logger.debug("REST : PUT - update");
		if ( service.update(pmsBrandDTO) ) {
			return ResponseEntity.ok().build(); // 200 OK, found and updated
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
		}
	}

	/**
 	 * Partial update for the given PK (if it exists )
	 *
	 * @param brandId
	 * @param pmsBrandDTO
	 * @return 200 updated or 404 not found
	 */
	@PatchMapping("/{brandId}")
	protected ResponseEntity<Void> partialUpdate(@PathVariable Long brandId, @RequestBody PmsBrandDTO pmsBrandDTO) {
    	logger.debug("REST : PATCH - partialUpdate");
    	if ( service.partialUpdate(brandId, pmsBrandDTO) ) {
    		return ResponseEntity.ok().build(); // OK, found and updated
    	}
    	else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
    	}
	}

	/**
	 * Delete by PK 
	 *
	 * @param brandId
	 * @return 204 deleted or 404 not found
	 */
	@DeleteMapping("/{brandId}")
	protected ResponseEntity<Void> deleteById(@PathVariable Long brandId) {
    	logger.debug("REST : DELETE - deleteById");
		if ( service.deleteById(brandId) ) {
			return ResponseEntity.noContent().build(); // 204 No content = "deleted"
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not deleted"
		}
	}

}
