/*
 * Created on 2024-05-02 ( 22:23:25 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;

import java.math.BigDecimal;

import java.util.Date;

/**
 * DTO class for "OmsOrder"
 *
 * @author Telosys
 *
 */
@Data
public class OmsOrderDTO implements Serializable {

  private static final long serialVersionUID = 1L;

  // --- PRIMARY KEY
  private Long id;
  // --- OTHER DATA FIELDS
  private Long memberId;
  private String orderSn;
  private Long couponId;
  private Date createTime;
  private String memberUsername;
  private BigDecimal totalAmount;
  private BigDecimal payAmount;
  private BigDecimal freightAmount;
  private BigDecimal promotionAmount;
  private BigDecimal integrationAmount;
  private BigDecimal couponAmount;
  private BigDecimal discountAmount;
  private Byte payType;
  private Byte sourceType;
  private Integer status;
  private String deliveryCompany;
  private String deliverySn;
  private Integer autoConfirmDay;
  private Integer integration;
  private Integer growth;
  private Byte billType;
  private String billHeader;
  private String billContent;
  private String billReceiverPhone;
  private String billReceiverEmail;
  private String receiverName;
  private String receiverPhone;
  private String receiverPostCode;
  private String receiverProvince;
  private String receiverCity;
  private String receiverRegion;
  private String receiverDetailAddress;
  private String note;
  private Integer confirmStatus;
  private Integer deleteStatus;
  private Integer useIntegration;
  private Date paymentTime;
  private Date deliveryTime;
  private Date receiveTime;
  private Date commentTime;
  private Date modifyTime;

  /**
   * Constructor
   */
  public OmsOrderDTO() {
    super();
  }
}
