/*
 * Created on 2024-05-02 ( 22:23:25 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;

import java.math.BigDecimal;


/**
 * DTO class for "OmsOrderItem"
 *
 * @author Telosys
 *
 */
@Data
public class OmsOrderItemDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private Long orderId ;
    private String orderSn ;
    private Long spuId ;
    private String spuName ;
    private String spuPic ;
    private String spuBrand ;
    private Long categoryId ;
    private Long skuId ;
    private String skuName ;
    private String skuPic ;
    private BigDecimal skuPrice ;
    private Integer skuQuantity ;
    private String skuAttrsVals ;
    private BigDecimal promotionAmount ;
    private BigDecimal couponAmount ;
    private BigDecimal integrationAmount ;
    private BigDecimal realAmount ;
    private Integer giftIntegration ;
    private Integer giftGrowth ;

    /**
     * Constructor
     */
    public OmsOrderItemDTO() {
		super();
    }
}
    

