/*
 * Created on 2024-05-02 ( 22:23:25 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;


/**
 * DTO class for "OmsOrderSetting"
 *
 * @author Telosys
 *
 */
@Data
public class OmsOrderSettingDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private Integer flashOrderOvertime ;
    private Integer normalOrderOvertime ;
    private Integer confirmOvertime ;
    private Integer finishOvertime ;
    private Integer commentOvertime ;
    private Byte memberLevel ;

    /**
     * Constructor
     */
    public OmsOrderSettingDTO() {
		super();
    }
}
    

