/*
 * Created on 2024-05-02 ( 22:23:25 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;

import java.math.BigDecimal;

import java.util.Date;


/**
 * DTO class for "OmsOrderReturnApply"
 *
 * @author Telosys
 *
 */
@Data
public class OmsOrderReturnApplyDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private Long orderId ;
    private Long skuId ;
    private String orderSn ;
    private Date createTime ;
    private String memberUsername ;
    private BigDecimal returnAmount ;
    private String returnName ;
    private String returnPhone ;
    private Boolean status ;
    private Date handleTime ;
    private String skuImg ;
    private String skuName ;
    private String skuBrand ;
    private String skuAttrsVals ;
    private Integer skuCount ;
    private BigDecimal skuPrice ;
    private BigDecimal skuRealPrice ;
    private String reason ;
    private String description述 ;
    private String descPics ;
    private String handleNote ;
    private String handleMan ;
    private String receiveMan ;
    private Date receiveTime ;
    private String receiveNote ;
    private String receivePhone ;
    private String companyAddress ;

    /**
     * Constructor
     */
    public OmsOrderReturnApplyDTO() {
		super();
    }
}
    

