/*
 * Created on 2024-05-02 ( 22:23:26 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;

import java.math.BigDecimal;

import java.util.Date;


/**
 * DTO class for "OmsPaymentInfo"
 *
 * @author Telosys
 *
 */
@Data
public class OmsPaymentInfoDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private String orderSn ;
    private Long orderId ;
    private String alipayTradeNo ;
    private BigDecimal totalAmount ;
    private String subject ;
    private String paymentStatus ;
    private Date createTime ;
    private Date confirmTime ;
    private String callbackContent ;
    private Date callbackTime ;

    /**
     * Constructor
     */
    public OmsPaymentInfoDTO() {
		super();
    }
}
    

