/*
 * Created on 2024-05-02 ( 22:23:26 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;

import java.math.BigDecimal;


/**
 * DTO class for "OmsRefundInfo"
 *
 * @author Telosys
 *
 */
@Data
public class OmsRefundInfoDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private Long orderReturnId ;
    private BigDecimal refund ;
    private String refundSn ;
    private Boolean refundStatus ;
    private Byte refundChannel ;
    private String refundContent ;

    /**
     * Constructor
     */
    public OmsRefundInfoDTO() {
		super();
    }
}
    

