/*
 * Created on 2024-05-02 ( 22:23:25 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import java.util.Date;
import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "OmsOrderReturnReason"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="oms_order_return_reason", catalog="gulimall-oms" )
public class OmsOrderReturnReason implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="name", length=200)
    private String     name ;

    @Column(name="sort")
    private Integer    sort ;

    @Column(name="status")
    private Boolean    status ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time")
    private Date       createTime ;

    /**
     * Constructor
     */
    public OmsOrderReturnReason() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(name);
  sb.append("|");
  sb.append(sort);
  sb.append("|");
  sb.append(status);
  sb.append("|");
  sb.append(createTime);
  return sb.toString(); 
 } 


}
