/*
 * Created on 2024-05-02 ( 22:23:25 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import java.math.BigDecimal;
import java.util.Date;
import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "OmsOrderReturnApply"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="oms_order_return_apply", catalog="gulimall-oms" )
public class OmsOrderReturnApply implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="order_id")
    private Long       orderId ;

    @Column(name="sku_id")
    private Long       skuId ;

    @Column(name="order_sn", length=32)
    private String     orderSn ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time")
    private Date       createTime ;

    @Column(name="member_username", length=64)
    private String     memberUsername ;

    @Column(name="return_amount")
    private BigDecimal returnAmount ;

    @Column(name="return_name", length=100)
    private String     returnName ;

    @Column(name="return_phone", length=20)
    private String     returnPhone ;

    @Column(name="status")
    private Boolean    status ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="handle_time")
    private Date       handleTime ;

    @Column(name="sku_img", length=500)
    private String     skuImg ;

    @Column(name="sku_name", length=200)
    private String     skuName ;

    @Column(name="sku_brand", length=200)
    private String     skuBrand ;

    @Column(name="sku_attrs_vals", length=500)
    private String     skuAttrsVals ;

    @Column(name="sku_count")
    private Integer    skuCount ;

    @Column(name="sku_price")
    private BigDecimal skuPrice ;

    @Column(name="sku_real_price")
    private BigDecimal skuRealPrice ;

    @Column(name="reason", length=200)
    private String     reason ;

    @Column(name="description述", length=500)
    private String     description述 ;

    @Column(name="desc_pics", length=2000)
    private String     descPics ;

    @Column(name="handle_note", length=500)
    private String     handleNote ;

    @Column(name="handle_man", length=200)
    private String     handleMan ;

    @Column(name="receive_man", length=100)
    private String     receiveMan ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="receive_time")
    private Date       receiveTime ;

    @Column(name="receive_note", length=500)
    private String     receiveNote ;

    @Column(name="receive_phone", length=20)
    private String     receivePhone ;

    @Column(name="company_address", length=500)
    private String     companyAddress ;

    /**
     * Constructor
     */
    public OmsOrderReturnApply() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(orderId);
  sb.append("|");
  sb.append(skuId);
  sb.append("|");
  sb.append(orderSn);
  sb.append("|");
  sb.append(createTime);
  sb.append("|");
  sb.append(memberUsername);
  sb.append("|");
  sb.append(returnAmount);
  sb.append("|");
  sb.append(returnName);
  sb.append("|");
  sb.append(returnPhone);
  sb.append("|");
  sb.append(status);
  sb.append("|");
  sb.append(handleTime);
  sb.append("|");
  sb.append(skuImg);
  sb.append("|");
  sb.append(skuName);
  sb.append("|");
  sb.append(skuBrand);
  sb.append("|");
  sb.append(skuAttrsVals);
  sb.append("|");
  sb.append(skuCount);
  sb.append("|");
  sb.append(skuPrice);
  sb.append("|");
  sb.append(skuRealPrice);
  sb.append("|");
  sb.append(reason);
  sb.append("|");
  sb.append(description述);
  sb.append("|");
  sb.append(descPics);
  sb.append("|");
  sb.append(handleNote);
  sb.append("|");
  sb.append(handleMan);
  sb.append("|");
  sb.append(receiveMan);
  sb.append("|");
  sb.append(receiveTime);
  sb.append("|");
  sb.append(receiveNote);
  sb.append("|");
  sb.append(receivePhone);
  sb.append("|");
  sb.append(companyAddress);
  return sb.toString(); 
 } 


}
