/*
 * Created on 2024-05-02 ( 22:23:25 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "OmsOrderSetting"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="oms_order_setting", catalog="gulimall-oms" )
public class OmsOrderSetting implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="flash_order_overtime")
    private Integer    flashOrderOvertime ;

    @Column(name="normal_order_overtime")
    private Integer    normalOrderOvertime ;

    @Column(name="confirm_overtime")
    private Integer    confirmOvertime ;

    @Column(name="finish_overtime")
    private Integer    finishOvertime ;

    @Column(name="comment_overtime")
    private Integer    commentOvertime ;

    @Column(name="member_level")
    private Byte       memberLevel ;

    /**
     * Constructor
     */
    public OmsOrderSetting() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(flashOrderOvertime);
  sb.append("|");
  sb.append(normalOrderOvertime);
  sb.append("|");
  sb.append(confirmOvertime);
  sb.append("|");
  sb.append(finishOvertime);
  sb.append("|");
  sb.append(commentOvertime);
  sb.append("|");
  sb.append(memberLevel);
  return sb.toString(); 
 } 


}
