/*
 * Created on 2024-05-02 ( 22:23:26 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import java.math.BigDecimal;
import java.util.Date;
import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "OmsPaymentInfo"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="oms_payment_info", catalog="gulimall-oms" )
public class OmsPaymentInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="order_sn", length=32)
    private String     orderSn ;

    @Column(name="order_id")
    private Long       orderId ;

    @Column(name="alipay_trade_no", length=50)
    private String     alipayTradeNo ;

    @Column(name="total_amount")
    private BigDecimal totalAmount ;

    @Column(name="subject", length=200)
    private String     subject ;

    @Column(name="payment_status", length=20)
    private String     paymentStatus ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time")
    private Date       createTime ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="confirm_time")
    private Date       confirmTime ;

    @Column(name="callback_content", length=4000)
    private String     callbackContent ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="callback_time")
    private Date       callbackTime ;

    /**
     * Constructor
     */
    public OmsPaymentInfo() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(orderSn);
  sb.append("|");
  sb.append(orderId);
  sb.append("|");
  sb.append(alipayTradeNo);
  sb.append("|");
  sb.append(totalAmount);
  sb.append("|");
  sb.append(subject);
  sb.append("|");
  sb.append(paymentStatus);
  sb.append("|");
  sb.append(createTime);
  sb.append("|");
  sb.append(confirmTime);
  sb.append("|");
  sb.append(callbackContent);
  sb.append("|");
  sb.append(callbackTime);
  return sb.toString(); 
 } 


}
