/*
 * Created on 2024-05-02 ( 19:42:32 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import com._yzhheng.constant.WareStatusEnum;
import com._yzhheng.persistence.entities.WmsWareOrderTask;
import com._yzhheng.persistence.entities.WmsWareOrderTaskDetail;

/**
 * Spring Data JPA repository for entity "WmsWareOrderTaskDetail" <br>
 * 
 * This repository extends PagingAndSortingRepository interface <br>
 * so it provides by default all the basic CRUD operations : <br>
 * findById, findAll, save, delete, etc <br>
 * with pagination and sorting : <br>
 * findAll(Pageable), findAll(Sort)<br>
 * 
 * This repository can be extended by adding specific "finders" methods<br>
 * To do so, see the "predicates conventions" for "derived query methods" in
 * Spring Data documentation
 * 
 * @author Telosys
 *
 */
public interface WmsWareOrderTaskDetailRepository extends JpaRepository<WmsWareOrderTaskDetail, Long> {

	@Query(value = "Select * from wms_ware_order_task_detail where task_id = :id AND lock_status = :lockWare", nativeQuery = true)
	List<WmsWareOrderTaskDetail> getAllLockedDetail(Long id, Integer lockWare);

	// Insert specific finders here

	// List<WmsWareOrderTaskDetail> findByXxx(String xxx);

	// List<WmsWareOrderTaskDetail> findByXxxStartingWith(String xxx);

	// List<WmsWareOrderTaskDetail> findByXxxContaining(String xxx);

	// List<WmsWareOrderTaskDetail> findByYyy(BigDecimal yyy);

	// List<WmsWareOrderTaskDetail> findByXxxContainingAndYyy(String xxx, BigDecimal
	// yyy);
}
