/*
 * Created on 2024-05-02 ( 14:45:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.services;

import java.util.List;
import java.util.Optional;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import com._yzhheng.persistence.entities.PmsBrand;
import com._yzhheng.persistence.repositories.PmsBrandRepository;
import com._yzhheng.rest.dto.PmsBrandDTO;
import com._yzhheng.rest.services.commons.GenericService;

/**
 * REST service for entity "PmsBrand" <br>
 * 
 * This service provides all the necessary operations required by the REST controller <br>
 * 
 * @author Telosys
 *
 */
@Service
public class PmsBrandService extends GenericService<PmsBrand, PmsBrandDTO> {

	private static final Logger logger = LoggerFactory.getLogger(PmsBrandService.class);

	private final PmsBrandRepository repository; // injected by constructor

	/**
	 * Constructor (usable for Dependency Injection)
	 * 
	 * @param repository the repository to be injected
	 */
	public PmsBrandService(PmsBrandRepository repository) {
		super(PmsBrand.class, PmsBrandDTO.class);
		this.repository = repository;
	}
	
	/**
	 * Returns the entity ID object from the given DTO
	 *
	 * @param dto
	 * @return
	 */
	private Long getEntityId(PmsBrandDTO dto) {
		return dto.getBrandId();
	}

	/**
	 * Finds all occurrences of the entity
	 *
	 * @return
	 */
	public List<PmsBrandDTO> findAll() {
		logger.debug("findAll()");
		Iterable<PmsBrand> all = repository.findAll();
		return entityListToDtoList(all);
	}

	/**
	 * Finds the entity identified by the given PK
	 *
	 * @param brandId 
	 * @return the entity or null if not found
	 */
	public PmsBrandDTO findById(Long brandId) {
		Long entityId = brandId;
		logger.debug("findById({})", entityId);
		Optional<PmsBrand> optionalEntity = repository.findById(entityId);
		return entityToDto(optionalEntity);
	}

	/**
	 * Saves the given entity with the given PK <br>
	 * "UPSERT" operation (updated if it exists or created if it does not exist)
	 *
	 * @param brandId 
	 * @param dto 
	 */
	public void save(Long brandId, PmsBrandDTO dto) {
		Long entityId = brandId;
		logger.debug("save({},{})", entityId, dto);
		// force PK in DTO (just to be sure to conform with the given PK) 
		dto.setBrandId(brandId);
		repository.save(dtoToEntity(dto));
	}

	/**
	 * Updates the given entity if it exists
	 *
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean update(PmsBrandDTO dto) {
		logger.debug("update({})", dto);
		if (repository.existsById(getEntityId(dto))) {
			repository.save(dtoToEntity(dto));
			return true; // find and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Updates partially the given entity if it exists
	 *
	 * @param brandId 
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean partialUpdate(Long brandId, PmsBrandDTO dto) {
		Long entityId = brandId;
		logger.debug("partialUpdate({}, {})", entityId, dto);
		Optional<PmsBrand> optionalEntity = repository.findById(entityId);
		if (optionalEntity.isPresent()) {
			PmsBrand entity = optionalEntity.get();
			// implement here the partial update
			// entity.setXxx(dto.getXxx());
			// etc ...
			repository.save(entity);
			return true; // find and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Creates the given entity
	 *
	 * @param dto
	 * @return true if created, false if already exists
	 */
	public boolean create(PmsBrandDTO dto) {
		logger.debug("create({})", dto);
		// auto-generated Primary Key
		repository.save(dtoToEntity(dto));
		return true; // always created
	}

	/**
	 * Deletes an entity by its PK
	 *
	 * @param brandId 
	 * @return true if deleted, false if not found
	 */
	public boolean deleteById(Long brandId) {
		Long entityId = brandId;
		logger.debug("deleteById({})", entityId);
		if (repository.existsById(entityId)) {
			repository.deleteById(entityId);
			return true; // find and deleted
		} else {
			return false; // not found (not deleted)
		}
	}

	// -----------------------------------------------------------------------------------------
	// Specific "finders"
	// -----------------------------------------------------------------------------------------
/***
	public List<PmsBrandDTO> findByTitle(String title) {
		logger.debug("findByTitle({})", title);
		// List<PmsBrand> list = repository.findByTitle(title);
		List<PmsBrand> list = repository.findByTitleContaining(title);
		return entityListToDtoList(list);
	}

	public List<PmsBrandDTO> findByPrice(BigDecimal price) {
		logger.debug("findByPrice({})", price);
		// List<PmsBrand> list = repository.findByTitle(title);
		List<PmsBrand> list = repository.findByPrice(price);
		return entityListToDtoList(list);
	}

	public List<PmsBrandDTO> findByTitleAndPrice(String title, BigDecimal price) {
		logger.debug("findByTitleAndPrice({}, {})", title, price);
		List<PmsBrand> list = repository.findByTitleContainingAndPrice(title, price);
		return entityListToDtoList(list);
	}
***/
}
