/*
 * Created on 2024-05-02 ( 14:45:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;


/**
 * DTO class for "PmsAttr"
 *
 * @author Telosys
 *
 */
@Data
public class PmsAttrDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long attrId ;
    //--- OTHER DATA FIELDS 
    private String attrName ;
    private Byte searchType ;
    private String icon ;
    private String valueSelect ;
    private Byte attrType ;
    private Long enable ;
    private Long catelogId ;
    private Byte showDesc ;

    /**
     * Constructor
     */
    public PmsAttrDTO() {
		super();
    }
}
    

