/*
 * Created on 2024-05-02 ( 14:45:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;


/**
 * DTO class for "PmsBrand"
 *
 * @author Telosys
 *
 */
@Data
public class PmsBrandDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long brandId ;
    //--- OTHER DATA FIELDS 
    private String name ;
    private String logo ;
    private String descript ;
    private Byte showStatus ;
    private String firstLetter ;
    private Integer sort ;

    /**
     * Constructor
     */
    public PmsBrandDTO() {
		super();
    }
}
    

