/*
 * Created on 2024-05-02 ( 14:45:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import java.util.List;

import com._yzhheng.persistence.entities.PmsCategory;

import lombok.Data;

/**
 * DTO class for "PmsCategory"
 *
 * @author Telosys
 *
 */
@Data
public class PmsCategoryDTO implements Serializable {

  private static final long serialVersionUID = 1L;

  // --- PRIMARY KEY
  private Long catId;
  // --- OTHER DATA FIELDS
  private String name;
  private Long parentCid;
  private Integer catLevel;
  private Byte showStatus;
  private Integer sort;
  private String icon;
  private String productUnit;
  private Integer productCount;

  private List<PmsCategory> children;

  /**
   * Constructor
   */
  public PmsCategoryDTO() {
    super();
  }
}
