/*
 * Created on 2024-05-02 ( 14:45:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;


/**
 * DTO class for "PmsProductAttrValue"
 *
 * @author Telosys
 *
 */
@Data
public class PmsProductAttrValueDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private Long spuId ;
    private Long attrId ;
    private String attrName ;
    private String attrValue ;
    private Integer attrSort ;
    private Byte quickShow ;

    /**
     * Constructor
     */
    public PmsProductAttrValueDTO() {
		super();
    }
}
    

