/*
 * Created on 2024-05-02 ( 14:45:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;

import java.math.BigDecimal;

import java.util.Date;


/**
 * DTO class for "PmsSpuInfo"
 *
 * @author Telosys
 *
 */
@Data
public class PmsSpuInfoDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private String spuName ;
    private String spuDescription ;
    private Long catalogId ;
    private Long brandId ;
    private BigDecimal weight ;
    private Byte publishStatus ;
    private Date createTime ;
    private Date updateTime ;

    /**
     * Constructor
     */
    public PmsSpuInfoDTO() {
		super();
    }
}
    

