/*
 * Created on 2024-05-02 ( 14:45:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;


/**
 * DTO class for "PmsSpuInfoDesc"
 *
 * @author Telosys
 *
 */
@Data
public class PmsSpuInfoDescDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long spuId ;
    //--- OTHER DATA FIELDS 
    private String decript ;

    /**
     * Constructor
     */
    public PmsSpuInfoDescDTO() {
		super();
    }
}
    

