/*
 * Created on 2024-05-02 ( 19:42:31 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import java.util.Date;
import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "UndoLog"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="undo_log", catalog="gulimall-wms" )
public class UndoLog implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="branch_id", nullable=false)
    private Long       branchId ;

    @Column(name="xid", nullable=false, length=100)
    private String     xid ;

    @Column(name="context", nullable=false, length=128)
    private String     context ;

    @Lob
    @Column(name="rollback_info", nullable=false)
    private byte[]     rollbackInfo ;

    @Column(name="log_status", nullable=false)
    private Integer    logStatus ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="log_created", nullable=false)
    private Date       logCreated ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="log_modified", nullable=false)
    private Date       logModified ;

    @Column(name="ext", length=100)
    private String     ext ;

    /**
     * Constructor
     */
    public UndoLog() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(branchId);
  sb.append("|");
  sb.append(xid);
  sb.append("|");
  sb.append(context);
  // attribute 'rollbackInfo' not usable (type = byte[])
  sb.append("|");
  sb.append(logStatus);
  sb.append("|");
  sb.append(logCreated);
  sb.append("|");
  sb.append(logModified);
  sb.append("|");
  sb.append(ext);
  return sb.toString(); 
 } 


}
