/*
 * Created on 2024-05-02 ( 19:42:32 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import java.math.BigDecimal;
import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "WmsPurchaseDetail"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="wms_purchase_detail", catalog="gulimall-wms" )
public class WmsPurchaseDetail implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="purchase_id")
    private Long       purchaseId ;

    @Column(name="sku_id")
    private Long       skuId ;

    @Column(name="sku_num")
    private Integer    skuNum ;

    @Column(name="sku_price")
    private BigDecimal skuPrice ;

    @Column(name="ware_id")
    private Long       wareId ;

    @Column(name="status")
    private Integer    status ;

    /**
     * Constructor
     */
    public WmsPurchaseDetail() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(purchaseId);
  sb.append("|");
  sb.append(skuId);
  sb.append("|");
  sb.append(skuNum);
  sb.append("|");
  sb.append(skuPrice);
  sb.append("|");
  sb.append(wareId);
  sb.append("|");
  sb.append(status);
  return sb.toString(); 
 } 


}
