/*
 * Created on 2024-05-02 ( 19:42:32 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import java.math.BigDecimal;
import java.util.Date;
import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "WmsPurchase"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="wms_purchase", catalog="gulimall-wms" )
public class WmsPurchase implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="assignee_id")
    private Long       assigneeId ;

    @Column(name="assignee_name", length=255)
    private String     assigneeName ;

    @Column(name="phone", length=13)
    private String     phone ;

    @Column(name="priority")
    private Integer    priority ;

    @Column(name="status")
    private Integer    status ;

    @Column(name="ware_id")
    private Long       wareId ;

    @Column(name="amount")
    private BigDecimal amount ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time")
    private Date       createTime ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_time")
    private Date       updateTime ;

    /**
     * Constructor
     */
    public WmsPurchase() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(assigneeId);
  sb.append("|");
  sb.append(assigneeName);
  sb.append("|");
  sb.append(phone);
  sb.append("|");
  sb.append(priority);
  sb.append("|");
  sb.append(status);
  sb.append("|");
  sb.append(wareId);
  sb.append("|");
  sb.append(amount);
  sb.append("|");
  sb.append(createTime);
  sb.append("|");
  sb.append(updateTime);
  return sb.toString(); 
 } 


}
