/*
 * Created on 2024-05-02 ( 19:42:32 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "WmsWareInfo"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="wms_ware_info", catalog="gulimall-wms" )
public class WmsWareInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="name", length=255)
    private String     name ;

    @Column(name="address", length=255)
    private String     address ;

    @Column(name="areacode", length=20)
    private String     areacode ;

    /**
     * Constructor
     */
    public WmsWareInfo() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(name);
  sb.append("|");
  sb.append(address);
  sb.append("|");
  sb.append(areacode);
  return sb.toString(); 
 } 


}
