/*
 * Created on 2024-05-02 ( 19:42:32 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "WmsWareSku"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="wms_ware_sku", catalog="gulimall-wms" )
public class WmsWareSku implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="sku_id")
    private Long       skuId ;

    @Column(name="ware_id")
    private Long       wareId ;

    @Column(name="stock")
    private Integer    stock ;

    @Column(name="sku_name", length=200)
    private String     skuName ;

    @Column(name="stock_locked")
    private Integer    stockLocked ;

    /**
     * Constructor
     */
    public WmsWareSku() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(skuId);
  sb.append("|");
  sb.append(wareId);
  sb.append("|");
  sb.append(stock);
  sb.append("|");
  sb.append(skuName);
  sb.append("|");
  sb.append(stockLocked);
  return sb.toString(); 
 } 


}
