/*
 * Created on 2024-05-02 ( 19:42:32 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "WmsWareOrderTaskDetail"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="wms_ware_order_task_detail", catalog="gulimall-wms" )
public class WmsWareOrderTaskDetail implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="sku_id")
    private Long       skuId ;

    @Column(name="sku_name", length=255)
    private String     skuName ;

    @Column(name="sku_num")
    private Integer    skuNum ;

    @Column(name="task_id")
    private Long       taskId ;

    @Column(name="ware_id")
    private Long       wareId ;

    @Column(name="lock_status")
    private Integer    lockStatus ;

    /**
     * Constructor
     */
    public WmsWareOrderTaskDetail() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(skuId);
  sb.append("|");
  sb.append(skuName);
  sb.append("|");
  sb.append(skuNum);
  sb.append("|");
  sb.append(taskId);
  sb.append("|");
  sb.append(wareId);
  sb.append("|");
  sb.append(lockStatus);
  return sb.toString(); 
 } 


}
