/*
 * Created on 2024-05-02 ( 14:45:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "PmsAttrAttrgroupRelation"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="pms_attr_attrgroup_relation", catalog="gulimall-pms" )
public class PmsAttrAttrgroupRelation implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="attr_id")
    private Long       attrId ;

    @Column(name="attr_group_id")
    private Long       attrGroupId ;

    @Column(name="attr_sort")
    private Integer    attrSort ;

    /**
     * Constructor
     */
    public PmsAttrAttrgroupRelation() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(attrId);
  sb.append("|");
  sb.append(attrGroupId);
  sb.append("|");
  sb.append(attrSort);
  return sb.toString(); 
 } 


}
