/*
 * Created on 2024-05-02 ( 14:45:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "PmsAttrGroup"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="pms_attr_group", catalog="gulimall-pms" )
public class PmsAttrGroup implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="attr_group_id", nullable=false)
    private Long       attrGroupId ;

    //--- OTHER DATA FIELDS 
    @Column(name="attr_group_name", length=20)
    private String     attrGroupName ;

    @Column(name="sort")
    private Integer    sort ;

    @Column(name="descript", length=255)
    private String     descript ;

    @Column(name="icon", length=255)
    private String     icon ;

    @Column(name="catelog_id")
    private Long       catelogId ;

    /**
     * Constructor
     */
    public PmsAttrGroup() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(attrGroupId);
  sb.append("|");
  sb.append(attrGroupName);
  sb.append("|");
  sb.append(sort);
  sb.append("|");
  sb.append(descript);
  sb.append("|");
  sb.append(icon);
  sb.append("|");
  sb.append(catelogId);
  return sb.toString(); 
 } 


}
