/*
 * Created on 2024-05-02 ( 14:45:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "PmsBrand"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="pms_brand", catalog="gulimall-pms" )
public class PmsBrand implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="brand_id", nullable=false)
    private Long       brandId ;

    //--- OTHER DATA FIELDS 
    @Column(name="name", length=50)
    private String     name ;

    @Column(name="logo", length=2000)
    private String     logo ;

    @Column(name="descript", length=2147483647)
    private String     descript ;

    @Column(name="show_status")
    private Byte       showStatus ;

    @Column(name="first_letter", length=1)
    private String     firstLetter ;

    @Column(name="sort")
    private Integer    sort ;

    /**
     * Constructor
     */
    public PmsBrand() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(brandId);
  sb.append("|");
  sb.append(name);
  sb.append("|");
  sb.append(logo);
  // attribute 'descript' not usable (type = String Long Text)
  sb.append("|");
  sb.append(showStatus);
  sb.append("|");
  sb.append(firstLetter);
  sb.append("|");
  sb.append(sort);
  return sb.toString(); 
 } 


}
