/*
 * Created on 2024-05-02 ( 14:45:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "PmsCommentReplay"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="pms_comment_replay", catalog="gulimall-pms" )
public class PmsCommentReplay implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="comment_id")
    private Long       commentId ;

    @Column(name="reply_id")
    private Long       replyId ;

    /**
     * Constructor
     */
    public PmsCommentReplay() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(commentId);
  sb.append("|");
  sb.append(replyId);
  return sb.toString(); 
 } 


}
