/*
 * Created on 2024-05-02 ( 14:45:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "PmsProductAttrValue"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="pms_product_attr_value", catalog="gulimall-pms" )
public class PmsProductAttrValue implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="spu_id")
    private Long       spuId ;

    @Column(name="attr_id")
    private Long       attrId ;

    @Column(name="attr_name", length=200)
    private String     attrName ;

    @Column(name="attr_value", length=200)
    private String     attrValue ;

    @Column(name="attr_sort")
    private Integer    attrSort ;

    @Column(name="quick_show")
    private Byte       quickShow ;

    /**
     * Constructor
     */
    public PmsProductAttrValue() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(spuId);
  sb.append("|");
  sb.append(attrId);
  sb.append("|");
  sb.append(attrName);
  sb.append("|");
  sb.append(attrValue);
  sb.append("|");
  sb.append(attrSort);
  sb.append("|");
  sb.append(quickShow);
  return sb.toString(); 
 } 


}
