/*
 * Created on 2024-05-02 ( 14:45:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "PmsSpuInfoDesc"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="pms_spu_info_desc", catalog="gulimall-pms" )
public class PmsSpuInfoDesc implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Column(name="spu_id", nullable=false)
    private Long       spuId ;

    //--- OTHER DATA FIELDS 
    @Column(name="decript", length=2147483647)
    private String     decript ;

    /**
     * Constructor
     */
    public PmsSpuInfoDesc() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(spuId);
  // attribute 'decript' not usable (type = String Long Text)
  return sb.toString(); 
 } 


}
