/*
 * Created on 2024-05-02 ( 14:45:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import java.math.BigDecimal;
import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "PmsSkuInfo"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="pms_sku_info", catalog="gulimall-pms" )
public class PmsSkuInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="sku_id", nullable=false)
    private Long       skuId ;

    //--- OTHER DATA FIELDS 
    @Column(name="spu_id")
    private Long       spuId ;

    @Column(name="sku_name", length=255)
    private String     skuName ;

    @Column(name="sku_desc", length=2000)
    private String     skuDesc ;

    @Column(name="catalog_id")
    private Long       catalogId ;

    @Column(name="brand_id")
    private Long       brandId ;

    @Column(name="sku_default_img", length=255)
    private String     skuDefaultImg ;

    @Column(name="sku_title", length=255)
    private String     skuTitle ;

    @Column(name="sku_subtitle", length=2000)
    private String     skuSubtitle ;

    @Column(name="price")
    private BigDecimal price ;

    @Column(name="sale_count")
    private Long       saleCount ;

    /**
     * Constructor
     */
    public PmsSkuInfo() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(skuId);
  sb.append("|");
  sb.append(spuId);
  sb.append("|");
  sb.append(skuName);
  sb.append("|");
  sb.append(skuDesc);
  sb.append("|");
  sb.append(catalogId);
  sb.append("|");
  sb.append(brandId);
  sb.append("|");
  sb.append(skuDefaultImg);
  sb.append("|");
  sb.append(skuTitle);
  sb.append("|");
  sb.append(skuSubtitle);
  sb.append("|");
  sb.append(price);
  sb.append("|");
  sb.append(saleCount);
  return sb.toString(); 
 } 


}
