/*
 * Created on 2024-05-02 ( 16:45:39 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import com._yzhheng.persistence.entities.UmsMember;

/**
 * Spring Data JPA repository for entity "UmsMember" <br>
 * 
 * This repository extends PagingAndSortingRepository interface <br>
 * so it provides by default all the basic CRUD operations : <br>
 * findById, findAll, save, delete, etc <br>
 * with pagination and sorting : <br>
 * findAll(Pageable), findAll(Sort)<br>
 * 
 * This repository can be extended by adding specific "finders" methods<br>
 * To do so, see the "predicates conventions" for "derived query methods" in
 * Spring Data documentation
 * 
 * @author Telosys
 *
 */
public interface UmsMemberRepository extends JpaRepository<UmsMember, Long> {

	@Query(value = "Select count(*) from ums_member where username = :userName", nativeQuery = true)
	int countUserName(String userName);

	// Insert specific finders here

	// List<UmsMember> findByXxx(String xxx);

	// List<UmsMember> findByXxxStartingWith(String xxx);

	// List<UmsMember> findByXxxContaining(String xxx);

	// List<UmsMember> findByYyy(BigDecimal yyy);

	// List<UmsMember> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);
}
