/*
 * Created on 2024-05-02 ( 16:20:01 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import java.math.BigDecimal;
import java.util.Date;
import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "SmsCoupon"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="sms_coupon", catalog="gulimall-sms" )
public class SmsCoupon implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="coupon_type")
    private Boolean    couponType ;

    @Column(name="coupon_img", length=2000)
    private String     couponImg ;

    @Column(name="coupon_name", length=100)
    private String     couponName ;

    @Column(name="num")
    private Integer    num ;

    @Column(name="amount")
    private BigDecimal amount ;

    @Column(name="per_limit")
    private Integer    perLimit ;

    @Column(name="min_point")
    private BigDecimal minPoint ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_time")
    private Date       startTime ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end_time")
    private Date       endTime ;

    @Column(name="use_type")
    private Boolean    useType ;

    @Column(name="note", length=200)
    private String     note ;

    @Column(name="publish_count")
    private Integer    publishCount ;

    @Column(name="use_count")
    private Integer    useCount ;

    @Column(name="receive_count")
    private Integer    receiveCount ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="enable_start_time")
    private Date       enableStartTime ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="enable_end_time")
    private Date       enableEndTime ;

    @Column(name="code", length=64)
    private String     code ;

    @Column(name="member_level")
    private Boolean    memberLevel ;

    @Column(name="publish")
    private Boolean    publish ;

    /**
     * Constructor
     */
    public SmsCoupon() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(couponType);
  sb.append("|");
  sb.append(couponImg);
  sb.append("|");
  sb.append(couponName);
  sb.append("|");
  sb.append(num);
  sb.append("|");
  sb.append(amount);
  sb.append("|");
  sb.append(perLimit);
  sb.append("|");
  sb.append(minPoint);
  sb.append("|");
  sb.append(startTime);
  sb.append("|");
  sb.append(endTime);
  sb.append("|");
  sb.append(useType);
  sb.append("|");
  sb.append(note);
  sb.append("|");
  sb.append(publishCount);
  sb.append("|");
  sb.append(useCount);
  sb.append("|");
  sb.append(receiveCount);
  sb.append("|");
  sb.append(enableStartTime);
  sb.append("|");
  sb.append(enableEndTime);
  sb.append("|");
  sb.append(code);
  sb.append("|");
  sb.append(memberLevel);
  sb.append("|");
  sb.append(publish);
  return sb.toString(); 
 } 


}
