/*
 * Created on 2024-05-02 ( 16:20:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "SmsCouponSpuRelation"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="sms_coupon_spu_relation", catalog="gulimall-sms" )
public class SmsCouponSpuRelation implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="coupon_id")
    private Long       couponId ;

    @Column(name="spu_id")
    private Long       spuId ;

    @Column(name="spu_name", length=255)
    private String     spuName ;

    /**
     * Constructor
     */
    public SmsCouponSpuRelation() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(couponId);
  sb.append("|");
  sb.append(spuId);
  sb.append("|");
  sb.append(spuName);
  return sb.toString(); 
 } 


}
