/*
 * Created on 2024-05-02 ( 16:20:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "SmsHomeSubject"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="sms_home_subject", catalog="gulimall-sms" )
public class SmsHomeSubject implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="name", length=200)
    private String     name ;

    @Column(name="title", length=255)
    private String     title ;

    @Column(name="sub_title", length=255)
    private String     subTitle ;

    @Column(name="status")
    private Boolean    status ;

    @Column(name="url", length=500)
    private String     url ;

    @Column(name="sort")
    private Integer    sort ;

    @Column(name="img", length=500)
    private String     img ;

    /**
     * Constructor
     */
    public SmsHomeSubject() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(name);
  sb.append("|");
  sb.append(title);
  sb.append("|");
  sb.append(subTitle);
  sb.append("|");
  sb.append(status);
  sb.append("|");
  sb.append(url);
  sb.append("|");
  sb.append(sort);
  sb.append("|");
  sb.append(img);
  return sb.toString(); 
 } 


}
