/*
 * Created on 2024-05-02 ( 16:20:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "SmsHomeSubjectSpu"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="sms_home_subject_spu", catalog="gulimall-sms" )
public class SmsHomeSubjectSpu implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="name", length=200)
    private String     name ;

    @Column(name="subject_id")
    private Long       subjectId ;

    @Column(name="spu_id")
    private Long       spuId ;

    @Column(name="sort")
    private Integer    sort ;

    /**
     * Constructor
     */
    public SmsHomeSubjectSpu() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(name);
  sb.append("|");
  sb.append(subjectId);
  sb.append("|");
  sb.append(spuId);
  sb.append("|");
  sb.append(sort);
  return sb.toString(); 
 } 


}
