/*
 * Created on 2024-05-02 ( 16:20:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import java.math.BigDecimal;
import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "SmsMemberPrice"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="sms_member_price", catalog="gulimall-sms" )
public class SmsMemberPrice implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="sku_id")
    private Long       skuId ;

    @Column(name="member_level_id")
    private Long       memberLevelId ;

    @Column(name="member_level_name", length=100)
    private String     memberLevelName ;

    @Column(name="member_price")
    private BigDecimal memberPrice ;

    @Column(name="add_other")
    private Boolean    addOther ;

    /**
     * Constructor
     */
    public SmsMemberPrice() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(skuId);
  sb.append("|");
  sb.append(memberLevelId);
  sb.append("|");
  sb.append(memberLevelName);
  sb.append("|");
  sb.append(memberPrice);
  sb.append("|");
  sb.append(addOther);
  return sb.toString(); 
 } 


}
