/*
 * Created on 2024-05-02 ( 16:20:03 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import java.util.Date;
import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "SmsSeckillSkuNotice"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="sms_seckill_sku_notice", catalog="gulimall-sms" )
public class SmsSeckillSkuNotice implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="member_id")
    private Long       memberId ;

    @Column(name="sku_id")
    private Long       skuId ;

    @Column(name="session_id")
    private Long       sessionId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="subcribe_time")
    private Date       subcribeTime ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="send_time")
    private Date       sendTime ;

    @Column(name="notice_type")
    private Boolean    noticeType ;

    /**
     * Constructor
     */
    public SmsSeckillSkuNotice() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(memberId);
  sb.append("|");
  sb.append(skuId);
  sb.append("|");
  sb.append(sessionId);
  sb.append("|");
  sb.append(subcribeTime);
  sb.append("|");
  sb.append(sendTime);
  sb.append("|");
  sb.append(noticeType);
  return sb.toString(); 
 } 


}
