/*
 * Created on 2024-05-02 ( 16:20:03 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import java.math.BigDecimal;
import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "SmsSeckillSkuRelation"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="sms_seckill_sku_relation", catalog="gulimall-sms" )
public class SmsSeckillSkuRelation implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="promotion_id")
    private Long       promotionId ;

    @Column(name="promotion_session_id")
    private Long       promotionSessionId ;

    @Column(name="sku_id")
    private Long       skuId ;

    @Column(name="seckill_price")
    private BigDecimal seckillPrice ;

    @Column(name="seckill_count")
    private BigDecimal seckillCount ;

    @Column(name="seckill_limit")
    private BigDecimal seckillLimit ;

    @Column(name="seckill_sort")
    private Integer    seckillSort ;

    /**
     * Constructor
     */
    public SmsSeckillSkuRelation() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(promotionId);
  sb.append("|");
  sb.append(promotionSessionId);
  sb.append("|");
  sb.append(skuId);
  sb.append("|");
  sb.append(seckillPrice);
  sb.append("|");
  sb.append(seckillCount);
  sb.append("|");
  sb.append(seckillLimit);
  sb.append("|");
  sb.append(seckillSort);
  return sb.toString(); 
 } 


}
