/*
 * Created on 2024-05-02 ( 16:20:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.persistence.entities;

import java.io.Serializable;

import java.util.Date;
import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "SmsSeckillPromotion"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="sms_seckill_promotion", catalog="gulimall-sms" )
public class SmsSeckillPromotion implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- OTHER DATA FIELDS 
    @Column(name="title", length=255)
    private String     title ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_time")
    private Date       startTime ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end_time")
    private Date       endTime ;

    @Column(name="status")
    private Byte       status ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time")
    private Date       createTime ;

    @Column(name="user_id")
    private Long       userId ;

    /**
     * Constructor
     */
    public SmsSeckillPromotion() {
		super();
    }
  
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(title);
  sb.append("|");
  sb.append(startTime);
  sb.append("|");
  sb.append(endTime);
  sb.append("|");
  sb.append(status);
  sb.append("|");
  sb.append(createTime);
  sb.append("|");
  sb.append(userId);
  return sb.toString(); 
 } 


}
