/*
 * Created on 2024-05-02 ( 16:20:01 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;

import java.math.BigDecimal;

import java.util.Date;


/**
 * DTO class for "SmsCoupon"
 *
 * @author Telosys
 *
 */
@Data
public class SmsCouponDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private Boolean couponType ;
    private String couponImg ;
    private String couponName ;
    private Integer num ;
    private BigDecimal amount ;
    private Integer perLimit ;
    private BigDecimal minPoint ;
    private Date startTime ;
    private Date endTime ;
    private Boolean useType ;
    private String note ;
    private Integer publishCount ;
    private Integer useCount ;
    private Integer receiveCount ;
    private Date enableStartTime ;
    private Date enableEndTime ;
    private String code ;
    private Boolean memberLevel ;
    private Boolean publish ;

    /**
     * Constructor
     */
    public SmsCouponDTO() {
		super();
    }
}
    

