/*
 * Created on 2024-05-02 ( 16:20:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;


/**
 * DTO class for "SmsCouponSpuCategoryRelation"
 *
 * @author Telosys
 *
 */
@Data
public class SmsCouponSpuCategoryRelationDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private Long couponId ;
    private Long categoryId ;
    private String categoryName ;

    /**
     * Constructor
     */
    public SmsCouponSpuCategoryRelationDTO() {
		super();
    }
}
    

