/*
 * Created on 2024-05-02 ( 16:20:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;


/**
 * DTO class for "SmsHomeSubjectSpu"
 *
 * @author Telosys
 *
 */
@Data
public class SmsHomeSubjectSpuDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private String name ;
    private Long subjectId ;
    private Long spuId ;
    private Integer sort ;

    /**
     * Constructor
     */
    public SmsHomeSubjectSpuDTO() {
		super();
    }
}
    

