/*
 * Created on 2024-05-02 ( 16:20:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;


/**
 * DTO class for "SmsHomeSubject"
 *
 * @author Telosys
 *
 */
@Data
public class SmsHomeSubjectDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private String name ;
    private String title ;
    private String subTitle ;
    private Boolean status ;
    private String url ;
    private Integer sort ;
    private String img ;

    /**
     * Constructor
     */
    public SmsHomeSubjectDTO() {
		super();
    }
}
    

