/*
 * Created on 2024-05-02 ( 16:20:03 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;

import java.util.Date;


/**
 * DTO class for "SmsSeckillSkuNotice"
 *
 * @author Telosys
 *
 */
@Data
public class SmsSeckillSkuNoticeDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private Long memberId ;
    private Long skuId ;
    private Long sessionId ;
    private Date subcribeTime ;
    private Date sendTime ;
    private Boolean noticeType ;

    /**
     * Constructor
     */
    public SmsSeckillSkuNoticeDTO() {
		super();
    }
}
    

