/*
 * Created on 2024-05-02 ( 16:20:03 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;

import java.math.BigDecimal;


/**
 * DTO class for "SmsSpuBounds"
 *
 * @author Telosys
 *
 */
@Data
public class SmsSpuBoundsDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private Long spuId ;
    private BigDecimal growBounds ;
    private BigDecimal buyBounds ;
    private Boolean work ;

    /**
     * Constructor
     */
    public SmsSpuBoundsDTO() {
		super();
    }
}
    

