/*
 * Created on 2024-05-02 ( 16:20:02 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com._yzhheng.rest.dto;

import java.io.Serializable;
import lombok.Data;

import java.util.Date;


/**
 * DTO class for "SmsSeckillPromotion"
 *
 * @author Telosys
 *
 */
@Data
public class SmsSeckillPromotionDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private Long id ;
    //--- OTHER DATA FIELDS 
    private String title ;
    private Date startTime ;
    private Date endTime ;
    private Byte status ;
    private Date createTime ;
    private Long userId ;

    /**
     * Constructor
     */
    public SmsSeckillPromotionDTO() {
		super();
    }
}
    

